name: UI Automated Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore WallProject
    - name: Build
      run: dotnet build --configuration Release --no-restore WallProject
    - name: Test
      run: dotnet test --no-restore WallProject/UIAutomatedTests
